SHOW USER;

SELCT SYSDATE 
FROM DUAL;

SELECT TO_CHAR (SYSDATE, 'DD-MON-YYYY HH:MI:SS')
FROM DUAL;

CREATE USER loja IDENTIFIED BY loja_senha;

GRANT connect, resource TO loja;

ALTER USER loja QUOTA 100M ON USERS;